feat: allow global --json flag usage
hashicorp/tfc-workflows-tooling pull request #58
Opened 2023-10-26 20:17 UTC by mjyocca

## Description

Add support for other command line tools such as `jq` by allowing a global `--json` flag argument.

Currently, we are outputting some in-progress/diagnostic information to stdout rather than to stderr. When a `--json` flag is detected regardless of position, we will send all information that is not the final result set to the standard error stream.

A new [writer](https://github.com/hashicorp/tfc-workflows-tooling/blob/0c61894f699825c228be23f6bd74e3dbd4f6cd38/internal/writer/writer.go#L12) package has been added to allow for better dependency injection for other packages.

## Testing plan

1. Execute various commands **without** the use of `--json` flag. No change in behavior and output.
1. Run and verify the following script works as expected, where the apply succeeds.

<details>
  <summary>script.sh</summary>

```bash
# set directory and workspace
DIR=""
WORKSPACE=""

CV_ID=$(go run . upload \
  --workspace=$WORKSPACE \
  --directory=$DIR \
  --json \
  | jq -r '.configuration_version_id'
)

echo $CV_ID

RUN_ID=$(go run . run create \
  --workspace=$WORKSPACE \
  --configuration_version=$CV_ID \
  --json \
  | jq -r '.run_id'
)

RES=$(
  go run . run apply \
  --run=$RUN_ID \
  --json  \
)

echo $RES
```

</details>

## External links

2023-10-31 20:51 UTC, ggambetti requested changes
Can you comment (in the description) the different aspects of application behaviour that are needed to support JSON output? It took me while to piece together the changes made across `meta.go`, `writer.go` and `cli.go`. And i'm not sure I understand it correctly.

I think there's two aspects to json support, but would like confirmation: moving most output to stderr, and outputting the run information as json?

2023-10-31 21:46 UTC, mjyocca commented
> Can you comment (in the description) the different aspects of application behaviour that are needed to support JSON output? It took me while to piece together the changes made across `meta.go`, `writer.go` and `cli.go`. And i'm not sure I understand it correctly.
> 
> I think there's two aspects to json support, but would like confirmation: moving most output to stderr, and outputting the run information as json?

Certainly, I also made some stylistic changes which probably made the requested changes less readable then needed to be.

Your assumptions are correct 😄. Moving current in-progress/diagnostic information to stderr when `--json` flag is detected. At this current moment we're outputting the result information as json, but this would allow us to different printed formats such as a prettier table etc.

2023-11-01 15:14 UTC, ggambetti reviewed
I think the thing that's most confusing to me is the use of both the `Writer` interface and `cli.Ui` as both have `Error` and `Output`. While that makes them more interchangeable, it also makes it much harder to determine which `Output` statement is supposed to write out the final json blob, and which ones are supposed to be converted to log entries.

Perhaps a single output interface that differentiated between logging data and json output would be clearer?

This might also address some of the `-json` double parsing, because the unified writer could expose a `*bool` which controlled the json setting and be populated by both the global flags and command specific flags.

2023-11-01 16:15 UTC, mjyocca commented
> I think the thing that's most confusing to me is the use of both the `Writer` interface and `cli.Ui` as both have `Error` and `Output`. While that makes them more interchangeable, it also makes it much harder to determine which `Output` statement is supposed to write out the final json blob, and which ones are supposed to be converted to log entries.
> 
> Perhaps a single output interface that differentiated between logging data and json output would be clearer?
> 
> This might also address some of the `-json` double parsing, because the unified writer could expose a `*bool` which controlled the json setting and be populated by both the global flags and command specific flags.

Good callout. So I did start down that path and limited direct access to `cli.Ui` by only the `Writer`, however ran into this problem of changing the Interface signature so I reverted for the sake of time.

Yeah great point on the double parsing, the first parsing does pass to the writer on application initialization, but left the second flag in the case of an trailing --json flag to prevent errors from the `flags package`. Wanted to avoid manipulating the arguments.

2023-11-02 21:28 UTC, ggambetti requested changes
Thanks for making the use of the `Writer` struct clearer with the `ResultX` functions. 👍🏻 I'd still like to cleanup flag parsing if possible.

2023-11-07 16:33 UTC, mjyocca commented
> Thanks for making the use of the `Writer` struct clearer with the `ResultX` functions. 👍🏻 I'd still like to cleanup flag parsing if possible.

I've added a separate PR that points to this branch to target the requested changes: https://github.com/hashicorp/tfc-workflows-tooling/pull/65

2023-11-07 20:53 UTC, ggambetti approved these changes
LGTM. Only some comment accuracy. 😄

2023-11-07 20:53 UTC, ggambetti commented on internal/command/meta.go
> +	// duplicate flag to prevent flags package error
nit: comment not accurate anymore.

2023-11-07 21:01 UTC, mjyocca commented on internal/command/meta.go
> +	// duplicate flag to prevent flags package error
Thanks for catching that! 😄

2023-11-08 16:11 UTC, ggambetti approved these changes

2023-11-08 17:58 UTC, merged